language: r

warnings_are_errors: true
r_check_args: --as-cran
sudo: required

services:
  - docker
  
r_github_packages:
  - antonellilab/outsider
  
after_success:
  - Rscript -e 'outsider::module_test(repo = "DomBennett/om..hello.world..1.0")'
